[[language]]
name = "svelte"
language-servers = [
  # "emmet-ls",
  "svelteserver",
  "vscode-html-language-server",
  "typescript-language-server",
  "tailwindcss-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "eslint-language-server",
  "typescript-language-server",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "emmet-ls",
  "typescript-language-server",
  "tailwindcss-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "latex"
language-servers = ["texlab", "typos"]

[language-server.typos]
command = "typos-lsp"

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
# environment = { NO_COLOR = "1" }

[language-server.deno-lsp.config.deno]
enable = true
# Uncomment to enable completion of unstable features of Deno
# unstable = true
# Uncomment to cache dependencies on save
# cacheOnSave = true
# Enable completion of importing from registries
# Enable completion of function calls
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }
# suggest = { imports = { hosts = { "https://deno.land" = true, "https://crux.land" = true, "https://x.nest.land" = true } } }
# Uncomment to enable inlay hints
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled  = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
